spring:
  application:
    name: contenedores-service

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/LogisticaContenedores
          jwk-set-uri: http://localhost:8080/realms/LogisticaContenedores/protocol/openid-connect/certs

  datasource:
    url: jdbc:postgresql://localhost:5432/logistica_contenedores_db
    username: lc_user
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

server:
  port: 8083


