server:
  port: 8083

spring:
  application:
    name: contenedores-service

  security:
    oauth2:
      resourceserver:
        jwt:
          # Usamos el nombre del contenedor Docker (keycloak)
          issuer-uri: http://keycloak:8080/realms/LogisticaContenedores
          jwk-set-uri: http://keycloak:8080/realms/LogisticaContenedores/protocol/openid-connect/certs

  datasource:
    # ⚠️ Nota: Si esto falla, cámbielo a jdbc:postgresql://postgres:5432/...
    url: jdbc:postgresql://host.docker.internal:5432/logistica_contenedores_db
    username: lc_user
    password: "1234"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    urls:
      - url: /v3/api-docs
        name: Contenedores API
  urls.primaryName: Contenedores API

# ✅ SOLUCIÓN AL ERROR: Definir el placeholder faltante para WebClient
camiones:
  service:
    url: http://camiones-service:8082 # Usa el nombre del servicio Docker